### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by andreldm** [andreldm/xfwm4-theme-generator#1]
Download any of the samples below, extract it at `~/.themes`, run `xfwm4-settings` and select "Theme-Generator-*" (you can rename it to whatever name you prefer).

### Adwaita
<a href="https://github.com/andreldm/xfwm4-theme-generator/files/5308377/Theme-Generator-Adwaita.zip">
<img alt="Adwaita" src="https://user-images.githubusercontent.com/599565/94740361-ecc82380-0348-11eb-8dce-7e835e8fefe2.png" width="50%" height="50%"></a>

### Adwaita-dark
<a href="https://github.com/andreldm/xfwm4-theme-generator/files/5308378/Theme-Generator-Adwaita-dark.zip">
<img alt="Adwaita-dark" src="https://user-images.githubusercontent.com/599565/94740343-e33ebb80-0348-11eb-98a2-c5f88b5addb6.png" width="50%" height="50%"></a>

### Greybird
<a href="https://github.com/andreldm/xfwm4-theme-generator/files/5308379/Theme-Generator-Greybird.zip">
<img alt="Greybird" src="https://user-images.githubusercontent.com/599565/94740345-e3d75200-0348-11eb-9a21-44ae21534c60.png" width="50%" height="50%"></a>

### Greybird-dark
<a href="https://github.com/andreldm/xfwm4-theme-generator/files/5308380/Theme-Generator-Greybird-dark.zip">
<img alt="Greybird-dark" src="https://user-images.githubusercontent.com/599565/94740371-f18cd780-0348-11eb-948f-7e54af61627b.png" width="50%" height="50%"></a>

**Comment by orschiro** [comment]
@andreldm the Adwaita one looks beautiful, thank you!

**Comment by andreldm** [comment]
Moved to README
